{
  config,
  lib,
  pkgs,
  inputs,
  ...
}:

{
  imports = [
    # Universal base (every host, incl. WSL)
    ../../base

    # Physical machine profile (audio, NetworkManager, printing, fonts)
    ../../profiles/physical.nix

    # User configuration
    ../../users/michael.nix

    # Hardware configuration (generated by nixos-generate-config; never hand-edit)
    ./hardware-configuration.nix
    # Hand-written hardware config (GPU, boot, filesystem options)
    ./hardware.nix

    # Host-specific configuration
    ./configuration.nix

    # Optional features (can be disabled per-host)
    ../../features/btrfs-snapshots.nix # Local /home snapshots (fast recovery)
    ../../features/backup.nix # Restic off-site backup (disaster recovery)
    ../../features/auto-update.nix # Weekly automatic system updates
    ../../features/virtualization.nix # libvirt/QEMU for VMs
    ../../features/containers.nix # Podman/OCI containers
    ../../features/gaming.nix # Gaming-specific programs
    ../../features/terminal-status-banner.nix # Health check on terminal startup

    # Services (optional, host-specific)

    # Desktop Environment
    ../../desktops/niri.nix
  ];

  system.stateVersion = "25.05";
}
